version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-admin
      MONGO_INITDB_ROOT_PASSWORD: YWRtaW4tcHc=

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: YWRtaW4tcHc=
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    links:
      - "mongo"

  vault:
    image: vault
    container_name: vault
    build:
      context: ./vault
    ports:
      - 8200:8200
    environment:
      VAULT_TOKEN: JwB0AGUAcwB0AF8AdABvAGsAZQBuACcA
      VAULT_DEV_ROOT_TOKEN_ID: JwB0AGUAcwB0AF8AdABvAGsAZQBuACcA
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    volumes:
      - ./logs:/vault/logs
